delimiter $$

CREATE TABLE `NODES_PARAM` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idNodes` int(11) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_NODES_TO_PARAM` (`idNodes`),
  CONSTRAINT `fk_NODES_TO_PARAM` FOREIGN KEY (`idNodes`) REFERENCES `NODES` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=latin1$$


